#!/usr/bin/env node

var link = require('fs-symlink'),
    path = require('path'),
    minimist = require('minimist'),
    indent = require('indenthero'),
    validateArguments = require('./validateArguments'),
    syntax = require('./syntax');

var args = minimist(process.argv.slice(2));

var validArgs = validateArguments(args);

if (!validArgs) {
    console.log('Usage:');

    for (var i = 0; i < syntax.length; i++) {
        var param = syntax[i];

        var example = indent('(' + param.example + ')');
        var output = indent(param.syntax + '\n' + example);

        console.log(output + '\n');
    }

    return;
}

var target = './';
if (args.target) {
    target = args.target;
}

var cwd = process.cwd();
var fromLink = path.join(cwd, target);
var toLink = path.join(cwd, 'node_modules', args.name);

link(fromLink, toLink, 'junction')
    .then(function () {
        console.log('Link created, from:');
        console.log('    ' + fromLink);
        console.log('to:');
        console.log('    ' + toLink);
    })
    .catch(function(err) {
        console.error(err);
    });
