#!/usr/bin/env node

var link = require('fs-symlink'),
    path = require('path'),
    minimist = require('minimist');

var args = minimist(process.argv.slice(2));

if (!args.name) {
    console.log('Usage:');
    console.log('    --name PACKAGE_NAME');
    console.log('        (--name modulink)');
    return;
}

var cwd = process.cwd();
var fromLink = cwd;
var toLink = path.join(cwd, 'node_modules', args.name);

link(fromLink, toLink, 'junction')
    .then(function () {
        console.log('Link created, from:');
        console.log('    ' + fromLink);
        console.log('to:');
        console.log('    ' + toLink);
    })
    .catch(function(err) {
        console.error(err);
    });
