#!/usr/bin/env node

var link = require('fs-symlink'),
    path = require('path'),
    minimist = require('minimist');

var args = minimist(process.argv.slice(2));

if (!args.name) {
    console.log('Usage:\n    --name PACKAGE_NAME (--name modulink)');
}

var cwd = process.cwd();
